// File generated by hand from `firebase apps:sdkconfig`, in place of
// FlutterFire CLI's own generator -- its Xcode-project-registration step
// needs a Ruby gem (xcodeproj) that fails to build against this Mac's
// system Ruby/Xcode SDK combination. The actual platform config files
// (ios/Runner/GoogleService-Info.plist, android/app/google-services.json)
// were downloaded successfully by the CLI before that step; only this
// Dart file had to be reconstructed manually. Re-run
// `flutterfire configure --project=a2-platform` to regenerate this
// properly once a working Ruby/xcodeproj setup exists.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQJEXA1A5nX9GQaY3Ezq4WovPq05i6x8',
    appId: '1:1040775128375:android:e835dfa2d553db928a26b2',
    messagingSenderId: '1040775128375',
    projectId: 'a2-platform',
    storageBucket: 'a2-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGogBPlsCJqNoNiOUcl770RVkHRRzW-gM',
    appId: '1:1040775128375:ios:b70f66515d701e928a26b2',
    messagingSenderId: '1040775128375',
    projectId: 'a2-platform',
    storageBucket: 'a2-platform.firebasestorage.app',
    iosBundleId: 'com.aaniaashley.a2',
  );

}